version: '3.5'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    hostname: mongo
    restart: always
    networks:
      - db
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
      #在这里输入 MongoDB 的 root 用户与密码，如果使用了此项，则不需要 --auth 参数
      MONGO_INITDB_ROOT_USERNAME: root   #表示 admin 数据库用户名
      MONGO_INITDB_ROOT_PASSWORD: 123456 #表示 admin 数据库密码
    volumes:
      - /etc/localtime:/etc/localtime:ro #设置容器时区与宿主机保持一致
      - /data0/mongo/data:/data/db
      - /data0/mongo/conf:/data/configdb
      - /data0/mongo/init/:/docker-entrypoint-initdb.d/
    command: mongod

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    links:
      - mongo:mongo
    depends_on:
      - mongo
    networks:
      - db
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root    #MongoDB admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456  #MongoDB admin password
      ME_CONFIG_BASICAUTH_USERNAME: root       #mongo-express web username
      ME_CONFIG_BASICAUTH_PASSWORD: 123456     #mongo-express web password

networks:
  db:
    driver: bridge